# This is the network config written by 'subiquity'
network:
  ethernets:
    ens18:
      dhcp4: true
      addresses:
      - 1.2.3.4/24
      gateway4: 192.168.0.255
      nameservers:
        addresses:
        - 8.8.8.8
  version: 2
